import {
  Accessibility,
  Armchair,
  ArrowUpNarrowWide,
  Award,
  Baby,
  BadgePercent,
  Bath,
  BedDouble,
  Bike,
  Building2,
  Bus,
  CalendarCheck,
  CalendarDays,
  CalendarSync,
  Car,
  CarFront,
  CarTaxiFront,
  Clock,
  Cookie,
  FileText,
  Compass,
  Globe,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Landmark,
  LayoutGrid,
  Leaf,
  type LucideIcon,
  type LucideProps,
  Luggage,
  MapPin,
  Maximize,
  Medal,
  Mountain,
  PackageOpen,
  PawPrint,
  Plane,
  Route,
  Ruler,
  Salad,
  Shield,
  ShieldCheck,
  Signal,
  Sofa,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  StretchHorizontal,
  Sun,
  Tag,
  ThumbsUp,
  Ticket,
  Timer,
  Trophy,
  Users,
  Utensils,
  UtensilsCrossed,
  Waves,
  Zap,
} from "lucide-react";

/**
 * Generic Lucide resolver for content configs (features, stats, detail specs).
 * Like {@link VerticalIcon} it keeps config files serialisable by storing icon
 * *names* as strings; register any icon used by content here.
 */
const ICON_MAP: Record<string, LucideIcon> = {
  BadgePercent,
  ShieldCheck,
  Headphones,
  CalendarCheck,
  Users,
  Building2,
  Globe,
  Star,
  // About / values
  Award,
  Heart,
  Leaf,
  // Home marketing bands (inspiration themes, awards)
  Compass,
  Landmark,
  Medal,
  Mountain,
  Plane,
  Sun,
  ThumbsUp,
  Trophy,
  Waves,
  // Detail-template specs
  Bath,
  BedDouble,
  Bus,
  CalendarDays,
  Car,
  Clock,
  FileText,
  LayoutGrid,
  MapPin,
  Maximize,
  Route,
  Ruler,
  Tag,
  Ticket,
  Timer,
  Utensils,
  // Flight extras — baggage, meals, comfort, assistance, protection, transfers
  // and the destination extras (eSIM, experiences, stays).
  Accessibility,
  Armchair,
  ArrowUpNarrowWide,
  Baby,
  Bike,
  CalendarSync,
  CarFront,
  CarTaxiFront,
  Cookie,
  HeartHandshake,
  HeartPulse,
  Luggage,
  PackageOpen,
  PawPrint,
  Salad,
  Shield,
  Signal,
  Sofa,
  Sprout,
  Stethoscope,
  StretchHorizontal,
  UtensilsCrossed,
  Zap,
};

interface LucideIconProps extends LucideProps {
  /** Registered icon name (e.g. "ShieldCheck"). */
  name: string;
}

/** Render a Lucide icon by name; falls back to a neutral glyph if unmapped. */
export function Icon({ name, ...props }: LucideIconProps) {
  const Cmp = ICON_MAP[name] ?? Sparkles;
  return <Cmp {...props} />;
}
