/**
 * Mock listing data for design build-out. Each array is fully typed against its
 * vertical entity in `types/catalog`. Images are remote (Unsplash) — see
 * `next.config.ts` remotePatterns. Consumed through the services layer
 * (`services/catalog`) so swapping to a real API touches only that seam.
 */

import type {
  Activity,
  Apartment,
  ConventionHall,
  Hotel,
  Resort,
  SharedRoom,
  Tour,
  Transport,
  Visa,
} from "@/types/catalog";
import {
  generateActivities,
  generateApartments,
  generateConventionHalls,
  generateHotels,
  generateResorts,
  generateSharedRooms,
  generateTours,
  generateTransport,
  generateVisas,
} from "@/lib/mock/listing-factory";

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

/**
 * Curated "hero" seeds — hand-authored, featured anchors shown first. The
 * exported arrays below concatenate these with a deterministic long tail from
 * the listing factory to reach StayOra's production volumes.
 */
const HOTELS_SEED: Hotel[] = [
  {
    id: "htl-1",
    slug: "the-grand-marina-resort",
    vertical: "hotels",
    title: "The Grand Marina Hotel",
    image: img("photo-1566073771259-6a8506099945"),
    location: { label: "Nice, France", city: "Nice", country: "France" },
    price: { amount: 189, original: 240, unit: "per night" },
    rating: 4.8,
    reviewCount: 1240,
    badges: ["Breakfast included"],
    featured: true,
    stars: 5,
    amenities: ["Free WiFi", "Pool", "Spa", "Parking"],
    roomType: "Deluxe sea-view rooms",
  },
  {
    id: "htl-2",
    slug: "azure-bay-boutique-hotel",
    vertical: "hotels",
    title: "Azure Bay Boutique Hotel",
    image: img("photo-1551882547-ff40c63fe5fa"),
    location: { label: "Santorini, Greece", city: "Santorini", country: "Greece" },
    price: { amount: 145, unit: "per night" },
    rating: 4.6,
    reviewCount: 860,
    stars: 4,
    amenities: ["Free WiFi", "Breakfast", "Rooftop bar"],
  },
  {
    id: "htl-3",
    slug: "cityscape-central-hotel",
    vertical: "hotels",
    title: "Cityscape Central Hotel",
    image: img("photo-1590490360182-c33d57733427"),
    location: { label: "Tokyo, Japan", city: "Tokyo", country: "Japan" },
    price: { amount: 210, original: 260, unit: "per night" },
    rating: 4.9,
    reviewCount: 2030,
    badges: ["Free cancellation"],
    stars: 5,
    amenities: ["Free WiFi", "Gym", "Restaurant"],
  },
];

const APARTMENTS_SEED: Apartment[] = [
  {
    id: "apt-1",
    slug: "sunlit-loft-old-town",
    vertical: "apartments",
    title: "Sunlit Loft in the Old Town",
    image: img("photo-1502672260266-1c1ef2d93688"),
    location: { label: "Lisbon, Portugal", city: "Lisbon", country: "Portugal" },
    price: { amount: 96, unit: "per night" },
    rating: 4.7,
    reviewCount: 412,
    featured: true,
    bedrooms: 2,
    bathrooms: 1,
    guests: 4,
    sizeSqm: 68,
  },
  {
    id: "apt-2",
    slug: "riverside-studio-apartment",
    vertical: "apartments",
    title: "Riverside Studio Apartment",
    image: img("photo-1522708323590-d24dbb6b0267"),
    location: { label: "Porto, Portugal", city: "Porto", country: "Portugal" },
    price: { amount: 74, original: 92, unit: "per night" },
    rating: 4.5,
    reviewCount: 288,
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    sizeSqm: 42,
  },
  {
    id: "apt-3",
    slug: "skyline-penthouse-suite",
    vertical: "apartments",
    title: "Skyline Penthouse Suite",
    image: img("photo-1560448204-e02f11c3d0e2"),
    location: { label: "Barcelona, Spain", city: "Barcelona", country: "Spain" },
    price: { amount: 168, unit: "per night" },
    rating: 4.9,
    reviewCount: 176,
    badges: ["Superhost"],
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    sizeSqm: 120,
  },
];

const RESORTS_SEED: Resort[] = [
  {
    id: "rst-1",
    slug: "palm-lagoon-all-inclusive",
    vertical: "resorts",
    title: "Palm Lagoon All-Inclusive Resort",
    image: img("photo-1571896349842-33c89424de2d"),
    location: { label: "Malé, Maldives", city: "Malé", country: "Maldives" },
    price: { amount: 420, original: 520, unit: "per night" },
    rating: 4.9,
    reviewCount: 980,
    featured: true,
    stars: 5,
    amenities: ["Private beach", "Spa", "5 restaurants", "Water sports"],
    boardType: "All inclusive",
  },
  {
    id: "rst-2",
    slug: "emerald-hills-spa-resort",
    vertical: "resorts",
    title: "Emerald Hills Spa Resort",
    image: img("photo-1520250497591-112f2f40a3f4"),
    location: { label: "Ubud, Indonesia", city: "Ubud", country: "Indonesia" },
    price: { amount: 235, unit: "per night" },
    rating: 4.7,
    reviewCount: 640,
    stars: 5,
    amenities: ["Infinity pool", "Yoga", "Spa"],
    boardType: "Half board",
  },
  {
    id: "rst-3",
    slug: "coral-reef-beach-resort",
    vertical: "resorts",
    title: "Coral Reef Beach Resort",
    image: img("photo-1602002418082-a4443e081dd1"),
    location: { label: "Phuket, Thailand", city: "Phuket", country: "Thailand" },
    price: { amount: 178, original: 210, unit: "per night" },
    rating: 4.6,
    reviewCount: 1120,
    stars: 4,
    amenities: ["Beachfront", "Pool", "Kids club"],
    boardType: "Breakfast",
  },
];

const SHARED_ROOMS_SEED: SharedRoom[] = [
  {
    id: "shr-1",
    slug: "backpackers-social-hub",
    vertical: "shared-rooms",
    title: "Backpackers Social Hub",
    image: img("photo-1555854877-bab0e564b8d5"),
    location: { label: "Bangkok, Thailand", city: "Bangkok", country: "Thailand" },
    price: { amount: 18, unit: "per bed / night" },
    rating: 4.4,
    reviewCount: 520,
    featured: true,
    bedsAvailable: 6,
    roomType: "Mixed dorm",
    amenities: ["Free WiFi", "Lockers", "Common kitchen"],
  },
  {
    id: "shr-2",
    slug: "harbour-view-hostel",
    vertical: "shared-rooms",
    title: "Harbour View Hostel",
    image: img("photo-1595576508898-0ad5c879a061"),
    location: { label: "Sydney, Australia", city: "Sydney", country: "Australia" },
    price: { amount: 32, original: 40, unit: "per bed / night" },
    rating: 4.5,
    reviewCount: 340,
    bedsAvailable: 4,
    roomType: "Female dorm",
    amenities: ["Free WiFi", "Breakfast", "Rooftop"],
  },
  {
    id: "shr-3",
    slug: "old-quarter-poshtel",
    vertical: "shared-rooms",
    title: "Old Quarter Poshtel",
    image: img("photo-1631049307264-da0ec9d70304"),
    location: { label: "Hanoi, Vietnam", city: "Hanoi", country: "Vietnam" },
    price: { amount: 14, unit: "per bed / night" },
    rating: 4.6,
    reviewCount: 610,
    bedsAvailable: 8,
    roomType: "Mixed dorm",
    amenities: ["Free WiFi", "Bar", "Tours desk"],
  },
];

const CONVENTION_HALLS_SEED: ConventionHall[] = [
  {
    id: "cvh-1",
    slug: "grand-horizon-ballroom",
    vertical: "convention-hall",
    title: "Grand Horizon Ballroom",
    image: img("photo-1519167758481-83f550bb49b3"),
    location: { label: "Dubai, UAE", city: "Dubai", country: "UAE" },
    price: { amount: 2400, unit: "per day" },
    rating: 4.8,
    reviewCount: 96,
    featured: true,
    capacity: 800,
    areaSqm: 1200,
    layouts: ["Theatre", "Banquet", "Classroom"],
  },
  {
    id: "cvh-2",
    slug: "metropolitan-conference-center",
    vertical: "convention-hall",
    title: "Metropolitan Conference Center",
    image: img("photo-1517457373958-b7bdd4587205"),
    location: { label: "Singapore", city: "Singapore", country: "Singapore" },
    price: { amount: 1650, original: 1900, unit: "per day" },
    rating: 4.7,
    reviewCount: 142,
    capacity: 450,
    areaSqm: 720,
    layouts: ["Theatre", "U-shape"],
  },
  {
    id: "cvh-3",
    slug: "riverside-events-pavilion",
    vertical: "convention-hall",
    title: "Riverside Events Pavilion",
    image: img("photo-1464366400600-7168b8af9bc3"),
    location: { label: "London, UK", city: "London", country: "UK" },
    price: { amount: 1980, unit: "per day" },
    rating: 4.6,
    reviewCount: 74,
    capacity: 300,
    areaSqm: 540,
    layouts: ["Banquet", "Reception"],
  },
];

const TRANSPORT_SEED: Transport[] = [
  {
    id: "trn-1",
    slug: "private-airport-transfer-sedan",
    vertical: "transport",
    title: "Private Airport Transfer — Sedan",
    image: img("photo-1549194388-f61be84a6e9e"),
    location: { label: "Paris, France", city: "Paris", country: "France" },
    price: { amount: 55, unit: "per trip" },
    rating: 4.8,
    reviewCount: 430,
    featured: true,
    transportType: "Private car",
    seats: 3,
    route: { from: "CDG Airport", to: "City center" },
    durationHours: 1,
  },
  {
    id: "trn-2",
    slug: "luxury-coach-city-to-coast",
    vertical: "transport",
    title: "Luxury Coach — City to Coast",
    image: img("photo-1544620347-c4fd4a3d5957"),
    location: { label: "Rome, Italy", city: "Rome", country: "Italy" },
    price: { amount: 28, original: 35, unit: "per trip" },
    rating: 4.5,
    reviewCount: 210,
    transportType: "Luxury coach",
    seats: 48,
    route: { from: "Rome", to: "Amalfi Coast" },
    durationHours: 3,
  },
  {
    id: "trn-3",
    slug: "island-hopping-ferry",
    vertical: "transport",
    title: "Island-Hopping Ferry",
    image: img("photo-1520255870062-bd79d3865de7"),
    location: { label: "Split, Croatia", city: "Split", country: "Croatia" },
    price: { amount: 22, unit: "per trip" },
    rating: 4.4,
    reviewCount: 158,
    transportType: "Ferry",
    seats: 120,
    route: { from: "Split", to: "Hvar" },
    durationHours: 1,
  },
];

const TOURS_SEED: Tour[] = [
  {
    id: "tur-1",
    slug: "highlights-of-tuscany-guided-tour",
    vertical: "tours",
    title: "Highlights of Tuscany — Guided Tour",
    image: img("photo-1543429776-2782fc8e1acd"),
    location: { label: "Tuscany, Italy", city: "Florence", country: "Italy" },
    price: { amount: 640, original: 780, unit: "per person" },
    rating: 4.9,
    reviewCount: 512,
    badges: ["Best seller"],
    featured: true,
    durationDays: 5,
    groupSize: 12,
    tourType: "Cultural",
  },
  {
    id: "tur-2",
    slug: "patagonia-trekking-adventure",
    vertical: "tours",
    title: "Patagonia Trekking Adventure",
    image: img("photo-1531794343509-1f5d3e0e0e0e"),
    location: { label: "Patagonia, Chile", city: "El Chaltén", country: "Chile" },
    price: { amount: 1290, unit: "per person" },
    rating: 4.8,
    reviewCount: 268,
    durationDays: 8,
    groupSize: 10,
    tourType: "Adventure",
  },
  {
    id: "tur-3",
    slug: "morocco-desert-and-medinas",
    vertical: "tours",
    title: "Morocco Desert & Medinas",
    image: img("photo-1489493887464-892be6d1daae"),
    location: { label: "Marrakech, Morocco", city: "Marrakech", country: "Morocco" },
    price: { amount: 720, original: 850, unit: "per person" },
    rating: 4.7,
    reviewCount: 394,
    durationDays: 6,
    groupSize: 14,
    tourType: "Cultural",
  },
];

const ACTIVITIES_SEED: Activity[] = [
  {
    id: "act-1",
    slug: "sunset-catamaran-cruise",
    vertical: "activities",
    title: "Sunset Catamaran Cruise",
    image: img("photo-1544551763-46a013bb70d5"),
    location: { label: "Ibiza, Spain", city: "Ibiza", country: "Spain" },
    price: { amount: 68, unit: "per person" },
    rating: 4.8,
    reviewCount: 720,
    badges: ["Free cancellation"],
    featured: true,
    durationHours: 3,
    category: "Water",
  },
  {
    id: "act-2",
    slug: "old-city-food-walking-tour",
    vertical: "activities",
    title: "Old City Food Walking Tour",
    image: img("photo-1414235077428-338989a2e8c0"),
    location: { label: "Istanbul, Türkiye", city: "Istanbul", country: "Türkiye" },
    price: { amount: 45, original: 55, unit: "per person" },
    rating: 4.9,
    reviewCount: 1040,
    durationHours: 4,
    category: "Food & drink",
  },
  {
    id: "act-3",
    slug: "hot-air-balloon-at-dawn",
    vertical: "activities",
    title: "Hot-Air Balloon at Dawn",
    image: img("photo-1507608616759-54f48f0af0ee"),
    location: { label: "Cappadocia, Türkiye", city: "Göreme", country: "Türkiye" },
    price: { amount: 175, unit: "per person" },
    rating: 4.9,
    reviewCount: 860,
    durationHours: 3,
    category: "Adventure",
  },
];

const VISAS_SEED: Visa[] = [
  {
    id: "vsa-1",
    slug: "schengen-tourist-visa",
    vertical: "visa",
    title: "Schengen Tourist Visa",
    image: img("photo-1488646953014-85cb44e25828"),
    location: { label: "Europe (26 countries)" },
    price: { amount: 120, unit: "per person" },
    rating: 4.7,
    reviewCount: 3200,
    featured: true,
    country: "Schengen Area",
    processingTime: "10–15 business days",
    validity: "90 days",
    entryType: "Multiple entry",
  },
  {
    id: "vsa-2",
    slug: "usa-b1-b2-visa-assistance",
    vertical: "visa",
    title: "USA B1/B2 Visa Assistance",
    image: img("photo-1485738422979-f5c462d49f74"),
    location: { label: "United States" },
    price: { amount: 185, unit: "per person" },
    rating: 4.6,
    reviewCount: 2100,
    country: "United States",
    processingTime: "3–5 weeks",
    validity: "Up to 10 years",
    entryType: "Multiple entry",
  },
  {
    id: "vsa-3",
    slug: "uae-tourist-visa-30-days",
    vertical: "visa",
    title: "UAE Tourist Visa (30 Days)",
    image: img("photo-1512453979798-5ea266f8880c"),
    location: { label: "United Arab Emirates" },
    price: { amount: 95, original: 110, unit: "per person" },
    rating: 4.8,
    reviewCount: 1480,
    country: "United Arab Emirates",
    processingTime: "2–4 business days",
    validity: "30 days",
    entryType: "Single entry",
  },
];

/* -------------------------------------------------------------------------
 * Exported catalogs — curated seeds first (featured anchors), then a seeded
 * deterministic long tail sized to StayOra's production volumes. Counts are
 * stable across renders because the factory never reads the clock or Math.random.
 * ---------------------------------------------------------------------- */

export const HOTELS: Hotel[] = [...HOTELS_SEED, ...generateHotels(49)];
export const APARTMENTS: Apartment[] = [...APARTMENTS_SEED, ...generateApartments(49)];
export const RESORTS: Resort[] = [...RESORTS_SEED, ...generateResorts(27)];
export const SHARED_ROOMS: SharedRoom[] = [...SHARED_ROOMS_SEED, ...generateSharedRooms(21)];
export const CONVENTION_HALLS: ConventionHall[] = [...CONVENTION_HALLS_SEED, ...generateConventionHalls(15)];
export const TRANSPORT: Transport[] = [...TRANSPORT_SEED, ...generateTransport(39)];
export const TOURS: Tour[] = [...TOURS_SEED, ...generateTours(41)];
export const ACTIVITIES: Activity[] = [...ACTIVITIES_SEED, ...generateActivities(79)];
export const VISAS: Visa[] = [...VISAS_SEED, ...generateVisas(23)];
