import {
  Activity,
  ArrowLeftRight,
  BadgePercent,
  Ban,
  Bell,
  BellRing,
  Boxes,
  CalendarCheck,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleHelp,
  CircleUser,
  Clock,
  Cloud,
  Coins,
  Database,
  FileBarChart,
  FileImage,
  Fingerprint,
  Gauge,
  Gavel,
  Globe,
  HardDrive,
  Image,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutPanelTop,
  LayoutTemplate,
  LifeBuoy,
  LineChart,
  type LucideIcon,
  type LucideProps,
  Mail,
  MailCheck,
  MailX,
  Menu,
  MessageSquare,
  MessageSquareQuote,
  Pause,
  Percent,
  PiggyBank,
  Plane,
  PlaneTakeoff,
  Receipt,
  RefreshCw,
  Route,
  Scale,
  Search,
  Server,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  Store,
  TicketCheck,
  Timer,
  TrendingUp,
  TriangleAlert,
  UserCog,
  Users,
  Wallet,
  Wrench,
} from "lucide-react";

/**
 * Dashboard icon registry.
 *
 * Menu/config data stores icon *names* as strings (JSON-safe, DB-drivable),
 * mirroring components/shared/lucide-icon. Register every icon the dashboard
 * navigation references here; unknown names fall back to a neutral glyph.
 */
const ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  LineChart,
  CalendarCheck,
  Boxes,
  Store,
  Users,
  Wallet,
  BadgePercent,
  FileBarChart,
  LayoutTemplate,
  Star,
  Globe,
  UserCog,
  ShieldCheck,
  KeyRound,
  SlidersHorizontal,
  LifeBuoy,
  CircleUser,
  Bell,
  MessageSquare,
  CircleHelp,
  ArrowLeftRight,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  Coins,
  Gavel,
  Landmark,
  Percent,
  PiggyBank,
  Receipt,
  Scale,
  TriangleAlert,
  FileImage,
  Image,
  HardDrive,
  LayoutPanelTop,
  Mail,
  MailCheck,
  MailX,
  Menu,
  MessageSquareQuote,
  Search,
  TrendingUp,
  Activity,
  Ban,
  BellRing,
  Clock,
  Cloud,
  Database,
  Fingerprint,
  Gauge,
  Layers,
  Pause,
  RefreshCw,
  Server,
  ShieldAlert,
  Wrench,
  Plane,
  PlaneTakeoff,
  Route,
  TicketCheck,
  Timer,
};

interface DashboardIconProps extends LucideProps {
  /** Registered icon name (e.g. "Wallet"). */
  name: string;
}

/** Render a dashboard icon by name; falls back to a neutral glyph if unmapped. */
export function DashboardIcon({ name, ...props }: DashboardIconProps) {
  const Cmp = ICON_MAP[name] ?? Sparkles;
  return <Cmp {...props} />;
}
